## 该cmake文件专门用来管理第三方库

include(${CMAKE_CURRENT_LIST_DIR}/ZSKY_global.cmake)

set(ZSKY_3RDPARTY_ALL_INCLUDE_DIR)   # 所有第三方库的包含目录
set(ZSKY_3RDPARTY_ALL_LIB_DIR)       # 所有第三方库的库目录
set(ZSKY_3RDPARTY_ALL_LIBRARIES)     # 所有第三方库的静态库
set(ZSKY_3RDPARTY_ALL_DLL)           # 所有第三方库的动态库
set(ZSKY_3RDPARTY_ALL_SOURCE)        # 所有第三方库的源文件，如果第三方库是源代码的话

# SDL2库
if(${USE_SDL2})
    include(${CMAKE_CURRENT_LIST_DIR}/3rdparty/SDL2.cmake)
    list(APPEND ZSKY_3RDPARTY_ALL_INCLUDE_DIR "${ZSKY_3RDPARTY_SDL_INCLUDE_DIR}")  
    list(APPEND ZSKY_3RDPARTY_ALL_LIB_DIR "${ZSKY_3RDPARTY_SDL_LIB_DIR}")
    list(APPEND ZSKY_3RDPARTY_ALL_LIBRARIES "${ZSKY_3RDPARTY_SDL_LIBRARIES}")
    list(APPEND ZSKY_3RDPARTY_ALL_DLL "${ZSKY_3RDPARTY_SDL_DLL}")
endif()

# freeglut库
if(${USE_FREEGLUT})
    include(${CMAKE_CURRENT_LIST_DIR}/3rdparty/freeglut.cmake)
    list(APPEND ZSKY_3RDPARTY_ALL_INCLUDE_DIR "${ZSKY_3RDPARTY_FREEGLUT_INCLUDE_DIR}")  
    list(APPEND ZSKY_3RDPARTY_ALL_LIB_DIR "${ZSKY_3RDPARTY_FREEGLUT_LIB_DIR}")
    list(APPEND ZSKY_3RDPARTY_ALL_LIBRARIES "${ZSKY_3RDPARTY_FREEGLUT_LIBRARIES}")
    list(APPEND ZSKY_3RDPARTY_ALL_DLL "${ZSKY_3RDPARTY_FREEGLUT_DLL}")
endif()

# glfw库
if(${USE_GLFW})
    include(${CMAKE_CURRENT_LIST_DIR}/3rdparty/glfw.cmake)
    list(APPEND ZSKY_3RDPARTY_ALL_INCLUDE_DIR "${ZSKY_3RDPARTY_GLFW_INCLUDE_DIR}")  
    list(APPEND ZSKY_3RDPARTY_ALL_LIB_DIR "${ZSKY_3RDPARTY_GLFW_LIB_DIR}")
    list(APPEND ZSKY_3RDPARTY_ALL_LIBRARIES "${ZSKY_3RDPARTY_GLFW_LIBRARIES}")
endif()

# OpenGL库
if(${USE_OPENGL2} OR ${USE_OPENGL3})
    find_package(OpenGL REQUIRED)
    if(${CMAKE_SYSTEM_NAME} MATCHES "Windows" OR ${CMAKE_SYSTEM_NAME} MATCHES "Darwin")  # Windows下由系统自动决定OpenGL版本
        list(APPEND ZSKY_3RDPARTY_ALL_LIBRARIES OpenGL::GL)
    elseif(${CMAKE_SYSTEM_NAME} MATCHES "Linux")  
    endif()
endif()

# Vulkan库
if(${USE_VULKAN})
    include(${CMAKE_CURRENT_LIST_DIR}/3rdparty/Vulkan.cmake)
    list(APPEND ZSKY_3RDPARTY_ALL_INCLUDE_DIR "${ZSKY_3RDPARTY_Vulkan_INCLUDE_DIR}")  
    list(APPEND ZSKY_3RDPARTY_ALL_LIB_DIR "${ZSKY_3RDPARTY_Vulkan_LIB_DIR}")
    list(APPEND ZSKY_3RDPARTY_ALL_LIBRARIES "${ZSKY_3RDPARTY_Vulkan_LIBRARIES}")
    list(APPEND ZSKY_3RDPARTY_ALL_DLL "${ZSKY_3RDPARTY_Vulkan_DLL}")
endif()

# DirectX库
# 使用DirectX作为渲染后端需要自己把下面的路径修改为自己电脑的Windows Kits的路径！
if(${USE_DIRECTX9})
    list(APPEND ZSKY_3RDPARTY_ALL_INCLUDE_DIR "D:/Windows Kits/10/Include/10.0.22621.0/um/x64")  
    list(APPEND ZSKY_3RDPARTY_ALL_LIB_DIR "D:/Windows Kits/10/Lib/10.0.22621.0/um/x64")
    list(APPEND ZSKY_3RDPARTY_ALL_LIBRARIES "d3d9.lib")
endif()

if(${USE_DIRECTX10})
    list(APPEND ZSKY_3RDPARTY_ALL_INCLUDE_DIR "D:/Windows Kits/10/Include/10.0.22621.0/um/x64")  
    list(APPEND ZSKY_3RDPARTY_ALL_LIB_DIR "D:/Windows Kits/10/Lib/10.0.22621.0/um/x64")
    list(APPEND ZSKY_3RDPARTY_ALL_LIBRARIES "d3d10.lib" "d3dcompiler.lib" "dxgi.lib")
endif()

if(${USE_DIRECTX11})
    list(APPEND ZSKY_3RDPARTY_ALL_INCLUDE_DIR "D:/Windows Kits/10/Include/10.0.22621.0/um/x64")  
    list(APPEND ZSKY_3RDPARTY_ALL_LIB_DIR "D:/Windows Kits/10/Lib/10.0.22621.0/um/x64")
    list(APPEND ZSKY_3RDPARTY_ALL_LIBRARIES "d3d11.lib" "d3dcompiler.lib" "dxgi.lib")
endif()

if(${USE_DIRECTX12})
    list(APPEND ZSKY_3RDPARTY_ALL_INCLUDE_DIR "D:/Windows Kits/10/Include/10.0.22621.0/um/x64")  
    list(APPEND ZSKY_3RDPARTY_ALL_LIB_DIR "D:/Windows Kits/10/Lib/10.0.22621.0/um/x64")
    list(APPEND ZSKY_3RDPARTY_ALL_LIBRARIES "d3d12.lib" "d3dcompiler.lib" "dxgi.lib")
endif()

# freetype库
include(${CMAKE_CURRENT_LIST_DIR}/3rdparty/freetype.cmake)
list(APPEND ZSKY_3RDPARTY_ALL_INCLUDE_DIR "${ZSKY_3RDPARTY_freetype_INCLUDE_DIR}")
list(APPEND ZSKY_3RDPARTY_ALL_LIB_DIR "${ZSKY_3RDPARTY_freetype_LIB_DIR}")
list(APPEND ZSKY_3RDPARTY_ALL_LIBRARIES "${ZSKY_3RDPARTY_freetype_LIBRARIES}")
list(APPEND ZSKY_3RDPARTY_ALL_DLL "${ZSKY_3RDPARTY_freetype_DLL}")

# 以下示例教导如何添加源代码版本的第三方库
#include(${CMAKE_CURRENT_LIST_DIR}/3rdparty/SSS.cmake)    # 假设该第三方库名为SSS
#list(APPEND ZSKY_3RDPARTY_ALL_INCLUDE_DIR "${ZSKY_3RDPARTY_SSS_INCLUDE_DIR}")  # 添加SSS库的头文件路径
#list(APPEND ZSKY_3RDPARTY_ALL_SOURCE "${ZSKY_3RDPARTY_SSS_SOURCE}")    # 添加SSS库的源代码